name: server
description: A Dart server app

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  json_annotation: ^2.0.0

dev_dependencies:
  # Your other dev_dependencies here
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
